# [Deep Learning with Pytorch](https://www.youtube.com/watch?v=V_xro1bcAuA)
Courtesy to:
- FreeCodeCamp
- Daniel Bourke (YT: @mrdbourke)
- [D Bourke GitHub](https://github.com/mrdbourke/pytorch-deep-learning)
- [Learn PyTorch](https://www.learnpytorch.io/)

In [2]:
import torch

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [20]:
MATRIX[0]

tensor([7, 8])

In [22]:
MATRIX.shape

torch.Size([2, 2])

In [26]:
# TENSOR # 3 square brackets pairs
TENSOR = torch.tensor([[[1, 2, 3]
                       ,[11, 22, 33]
                       ,[111, 222, 333]]])
TENSOR

tensor([[[  1,   2,   3],
         [ 11,  22,  33],
         [111, 222, 333]]])

In [28]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])

In [36]:
TENSOR[0]

tensor([[  1,   2,   3],
        [ 11,  22,  33],
        [111, 222, 333]])

In [46]:
TENSOR_2 = torch.tensor([[[1, 2, 3]
                       ,[11, 22, 33]
                       ,[111, 222, 333]]
                        , [[4, 5, 6]
                       ,[44, 55, 66]
                       ,[444, 555, 666]]])

In [48]:
TENSOR_2.ndim

3

In [50]:
TENSOR_2.shape

torch.Size([2, 3, 3])

In [58]:
TENSOR_2[1]

tensor([[  4,   5,   6],
        [ 44,  55,  66],
        [444, 555, 666]])