# [Deep Learning with Pytorch](https://www.youtube.com/watch?v=V_xro1bcAuA)
Courtesy to:
- FreeCodeCamp
- Daniel Bourke (YT: @mrdbourke)
- [D Bourke GitHub](https://github.com/mrdbourke/pytorch-deep-learning)
- [Learn PyTorch](https://www.learnpytorch.io/)
- [PyTorch Docs](https://pytorch.org/docs/stable/index.html)
- [Data types](https://pytorch.org/docs/main/tensors.html)

Personal notes:
- this notebook uses ai-env kernel

In [1]:
import torch

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as Python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR # 3 square brackets pairs
TENSOR = torch.tensor([[[1, 2, 3]
                       ,[11, 22, 33]
                       ,[111, 222, 333]]])
TENSOR

tensor([[[  1,   2,   3],
         [ 11,  22,  33],
         [111, 222, 333]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[  1,   2,   3],
        [ 11,  22,  33],
        [111, 222, 333]])

In [16]:
TENSOR_2 = torch.tensor([[[1, 2, 3]
                       ,[11, 22, 33]
                       ,[111, 222, 333]]
                        , [[4, 5, 6]
                       ,[44, 55, 66]
                       ,[444, 555, 666]]])

In [17]:
TENSOR_2.ndim

3

In [18]:
TENSOR_2.shape

torch.Size([2, 3, 3])

In [19]:
TENSOR_2[1]

tensor([[  4,   5,   6],
        [ 44,  55,  66],
        [444, 555, 666]])

### Random tensors

In [20]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5883, 0.6202, 0.5673, 0.1439],
        [0.4933, 0.9046, 0.9270, 0.5275],
        [0.4950, 0.8220, 0.1515, 0.2592]])

In [21]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channel (rgb), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [22]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

UserWarning: `torch.range` is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).

In [25]:
# use torch.arange()
one_to_ten = torch.arange(0, 11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
_arange = torch.arange(start=0, end=1000, step=77)
_arange

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype; use `tensor.dtype`
1. Tensors not right shape; use `tensor.shape`
1. Tensors not on the right device; use `tensor.device`

In [28]:
# float 32 tensor as the default
float_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_tensor, float_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [29]:
float_tensor = torch.tensor([3.0, 6.0, 9.0]
                            , dtype=None
                            , device=None # default: "cpu"; can try "cuda"
                            , requires_grad=False)
float_tensor, float_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [30]:
# getting float-16-typed tensor from the previous `float_tensor` using .type(torch.float16) or .type(torch.half)
float_16_tensor = float_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_half_tensor = float_tensor.type(torch.half)
float_half_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_tensor * float_half_tensor # multiplying tensors with different datatypes

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
int_32_tensor * float_half_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [35]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8109, 0.5139, 0.4128, 0.6751],
        [0.4528, 0.2465, 0.9962, 0.4993],
        [0.4882, 0.4498, 0.9168, 0.3006]])

In [36]:
print(some_tensor)
print(f"data type: {some_tensor.dtype}")
print(f"shape: {some_tensor.shape}")
print(f"device: {some_tensor.device}")

tensor([[0.8109, 0.5139, 0.4128, 0.6751],
        [0.4528, 0.2465, 0.9962, 0.4993],
        [0.4882, 0.4498, 0.9168, 0.3006]])
data type: torch.float32
shape: torch.Size([3, 4])
device: cpu


In [37]:
some_tensor.size() # `size` method is the same as `shape` attribute

torch.Size([3, 4])

### Tensor Operations
Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

addition

In [39]:
# addition
_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
_tensor += 10
_tensor

tensor([[11, 12, 13],
        [14, 15, 16]])

In [59]:
# addition
_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.add(_tensor, 10)

tensor([[11, 12, 13],
        [14, 15, 16]])

multiplication

In [57]:
# multiplication
_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
_tensor *= 10
_tensor

tensor([[10, 20, 30],
        [40, 50, 60]])

In [58]:
# multiplication
_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.mul(_tensor, 10)

tensor([[10, 20, 30],
        [40, 50, 60]])

subtraction

In [44]:
# subtraction
_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
_tensor -= 10
_tensor

tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [61]:
# subtraction
_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.sub(_tensor, 10)

tensor([[-9, -8, -7],
        [-6, -5, -4]])

### Multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

Element-wise multiplication

In [56]:
_tensor = torch.tensor([1, 2, 3])
print(_tensor, '*', _tensor)
print('Equals: ', _tensor * _tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


Matrix multiplication

In [64]:
_tensor = torch.tensor([1, 2, 3])
torch.matmul(_tensor, _tensor)

tensor(14)

In [86]:
_tensor = torch.tensor([1, 2, 3])
_tensor2 = torch.tensor([1, 2, 3, 4])
try:
    print(torch.matmul(_tensor, _tensor2))
    print('not an error')
except Exception as e:
    print('error:', str(e))

error: inconsistent tensor size, expected tensor [3] and src [4] to have the same number of elements, but got 3 and 4 elements respectively


In [84]:
_tensor = torch.tensor([[1, 2, 3], [1, 2, 3]])
_tensor2 = torch.tensor([1, 2, 3])
try:
    print(torch.matmul(_tensor, _tensor2))
    print('not an error')
except Exception as e:
    print('error:', str(e))

tensor([14, 14])
not an error


In [85]:
_tensor = torch.tensor([1, 2, 3])
_tensor2 = torch.tensor([[1, 2, 3], [1, 2, 3]])
try:
    print(torch.matmul(_tensor, _tensor2))
    print('not an error')
except Exception as e:
    print('error:', str(e))

error: mat1 and mat2 shapes cannot be multiplied (1x3 and 2x3)


continue: 2:25

In [53]:
# division
# _tensor = torch.tensor([[10, 20, 30], [40, 50, 60]])
# _tensor /= 10
# _tensor